FROM hasura/graphql-engine:pull3252-1664d30e

ENV HASURA_GRAPHQL_MIGRATIONS_DIR /migrations \
    HASURA_GRAPHQL_ENABLE_CONSOLE true \
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE anonymous \
    HASURA_GRAPHQL_DATABASE_URL \
    HASURA_GRAPHQL_ADMIN_SECRET

COPY migrations /migrations
